baseURL = 'http://localhost:1313/'
languageCode = 'pt-br'
title = 'CECAS/SBC'
theme = 'PaperMod'

[params]
  # PaperMod theme parameters
  homeInfoParams = { Title = "Comissão Especial de Computação Aplicada à Saúde", Content = "A Comissão Especial de Computação Aplicada à Saúde (CECAS) foi aprovada em julho de 2007 e tem por objetivo auxiliar a SBC no fomento e no desenvolvimento da área de Computação aplicada à saúde, criando um espaço de divulgação e integração de pesquisas." }
  
  # Enable search
  fuseOpts = { isCaseSensitive = false, shouldSort = true, location = 0, distance = 1000, threshold = 0.4, minMatchCharLength = 0, keys = ["title", "permalink", "summary", "content"] }

[menu]
  [[menu.main]]
    identifier = "inicio"
    name = "Início"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "documentos"
    name = "Documentos"
    url = "/documentos/"
    weight = 2
  [[menu.main]]
    identifier = "eventos"
    name = "Eventos"
    url = "/eventos/"
    weight = 3
  [[menu.main]]
    identifier = "publicacoes"
    name = "Publicações"
    url = "/eventos/publicacoes/"
    weight = 4
  [[menu.main]]
    identifier = "grupos-pesquisa"
    name = "Grupos de Pesquisa"
    url = "/grupos-de-pesquisa/"
    weight = 5
  [[menu.main]]
    identifier = "memorial"
    name = "Memorial Artur Ziviani"
    url = "/memorial-artur-ziviani/"
    weight = 6
